#! /bin/sh
NAME="python"
DESC="Install Python >= gtever and < ltver"
REQS=""
OPTS='
  { "params": ["gtever", "ltver"],
    "defaults": { "gtever": "2.7", "ltver": "3.0" } }
'

#SFILE=$(mktemp)
#echo $OPTS | ../JSON.sh/JSON.sh >> $SFILE
#echo $DEFAULT_OPTS | ../JSON.sh/JSON.sh >> $SFILE
#
#param () {
#    [ $# = 1 ] || return 1
#    local PLINE=$(grep '^\["params"\]\["'"$1"'"\]' $SFILE)
#    [ $? = 0 ] || return 1
#    echo $PLINE | awk '{ print $2; }' | tr -d '"'
#    return 0
#}

param_check () {
    for p in $(echo "$OPTS" |
               ../JSON.sh/JSON.sh |
               grep '^\["params"\]' |
               awk '{ print $2; }' | tr -d '"'); do

        if !(param $p); then
            return 1
        fi

    done
    return 0
}

param () {
    [ $# = 1 ] || return 1
    local PLINE=""
    local VAL=""
    PLINE=$(echo "$PARAMS" | ../JSON.sh/JSON.sh | grep '^\["'"$1"'"\]')
    if [ $? = 1 ]; then
        PLINE=$(echo "$OPTS" | ../JSON.sh/JSON.sh | grep '^\["defaults"\]\["'"$1"'"\]')
        if [ $? = 1 ]; then
            return 1
        fi
    fi
    echo "$PLINE" | awk '{ print $2; }' | tr -d '"'
    return 0
}

deploy_test () {
    echo $(param gtever)
    which python || check
    python -c "import sys;\
        exit(sys.version_info.major >= $(param gtever | tr "." " "))"
    python -c 'import sys;\
               exit(sys.version_info.major != 2 or
               sys.version_info < 7)' || check
}














